# Generated by Django 3.2 on 2021-05-16 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('slug', models.SlugField()),
                ('is_private', models.BooleanField(default=False)),
                ('course_img', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lecture_no', models.AutoField(primary_key=True, serialize=False)),
                ('lecture_name', models.CharField(max_length=200)),
                ('lecture_slug', models.SlugField()),
                ('video_url', models.CharField(max_length=200)),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='LectureMaterial',
            fields=[
                ('materialno', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.FileField(upload_to='lecture/material/')),
                ('lecture_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lecture')),
            ],
        ),
    ]
