# Generated by Django 3.2 on 2021-05-07 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210507_1145'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inside_cart',
            name='receiver_username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insidecart_receiver', to='accounts.student'),
        ),
    ]
