# Generated by Django 3.2 on 2021-05-07 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210507_1145'),
    ]

    operations = [
    ]
