# Generated by Django 3.2 on 2021-05-11 12:53
import datetime

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210511_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluates',
            name='reply_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
