# Generated by Django 3.2 on 2021-05-14 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210514_1740'),
        ('adminpanel', '0001_initial'),
        ('main', '0007_auto_20210512_1439'),
    ]

    operations = [

    ]
