# Generated by Django 3.2 on 2021-05-13 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210513_1514'),
        ('main', '0007_auto_20210512_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avg_Rate',
            fields=[
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses.course')),
                ('avg', models.FloatField()),
            ],
        ),
    ]
