# Generated by Django 3.2 on 2021-04-22 23:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('ad_username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cno', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('situation', models.CharField(choices=[('Pending', 'Pnd'), ('Declined', 'Dcl'), ('Approved', 'Appr')], default='Pending', max_length=8)),
                ('is_private', models.BooleanField(default=False)),
                ('course_img', models.ImageField(upload_to='thumbnails/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lecture_no', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('lecture_name', models.CharField(max_length=200)),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topicname', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.user')),
                ('description', models.TextField()),
            ],
            bases=('main.user',),
        ),
        migrations.CreateModel(
            name='SiteAdmin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.user')),
                ('ssn', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
            bases=('main.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.user')),
                ('description', models.TextField()),
            ],
            bases=('main.user',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postno', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('post', models.TextField()),
                ('lecture_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lecture')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='LectureMaterial',
            fields=[
                ('materialno', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('material', models.FileField(upload_to='lecture/material/')),
                ('lecture_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Topic',
            fields=[
                ('course_topic_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('topicname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignmentno', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('assignment', models.FileField(upload_to='lecture/assignments/')),
                ('lecture_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('advertisementno', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('advertisement', models.CharField(max_length=512)),
                ('status', models.SmallIntegerField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('startdate', models.DateField()),
                ('finishdate', models.DateField()),
                ('ad_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertiser')),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='Wishes',
            fields=[
                ('wishes_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('teach_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('lecture_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Takes_note',
            fields=[
                ('note_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('lecture_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lecture')),
                ('s_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('refund_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=500)),
                ('status', models.SmallIntegerField(default=0)),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('s_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('finishes_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField()),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Quest_answ',
            fields=[
                ('answer_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='answer', serialize=False, to='main.post')),
                ('question_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='main.post')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('prog_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('lecture_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lecture')),
                ('s_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Interested_in',
            fields=[
                ('interested_in_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('s_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Inside_Cart',
            fields=[
                ('inside_cart_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='main.user')),
                ('receiver_username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insidecart_receiver', to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('gift_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='main.user')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Finishes',
            fields=[
                ('finishes_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(null=True)),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluates',
            fields=[
                ('refund_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.refundrequest')),
                ('reply_date', models.DateField()),
                ('admin_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.siteadmin')),
            ],
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('enroll_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('startdate', models.DateTimeField(auto_created=True)),
                ('discountno', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('newprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('finishdate', models.DateTimeField()),
                ('situation', models.SmallIntegerField()),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('admin_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.siteadmin')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.instructor'),
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('cont_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('creation_date', models.DateField(auto_created=True)),
                ('comp_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('s_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('ann_date', models.DateField(auto_created=True)),
                ('ann_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('ann_text', models.TextField()),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('i_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.instructor')),
            ],
        ),
    ]
